services:
  postgres: 
    image: postgres:latest
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=postgrespw
    ports: 
      - 5432:5432
    # volumes: 
    #   - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
#     volumes:
#       - mongodata:/var/lib/mongodb/data
#
# volumes:
#   pgdata:
#   mongodata:
