services:
  postgres: 
    image: postgres:latest
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=postgrespw
    ports: 
      - 5432:5432
    volumes: 
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
