apiVersion: apps/v1
kind: Deployment
metadata:
  name: bid-svc
spec:
  selector:
    matchLabels:
      app: bid-svc
  template:
    metadata:
      labels:
        app: bid-svc
    spec:
      containers:
        - name: bid-svc
          image: liamstan/bid-svc:latest
          # imagePullPolicy: Never # always use local image
          env:
            - name: RabbitMQ__Host
              value: rabbit-clusterip
            - name: RabbitMQ__Username
              valueFrom:
                secretKeyRef:
                  name: bid-secret
                  key: rabbitUn
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: bid-secret
                  key: rabbitPw
            - name: ConnectionStrings__BidDbConnection
              valueFrom:
                secretKeyRef:
                  name: bid-secret
                  key: connString
            - name: GrpcAuction
              value: http://auction-clusterip:7777
            - name: IdentityServiceUrl
              value: https://id.dev-liamstan.site
---
apiVersion: v1
kind: Service
metadata:
  name: bid-clusterip
spec:
  type: ClusterIP
  selector:
    app: bid-svc
  ports:
    - port: 80
      targetPort: 80
