name: deploy-app

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "frontend/web-app/**"

env:
  REGISTERY_IMAGE: "liamstan/wab-app"
  DOCKERFILE: "frontend/web-app/Dockerfile"
  DEPLOYMENT_NAME: "webapp"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_PASSWORD}}
      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}"
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: ${{ env.REGISTERY_IMAGE }}:latest
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save carsties-k8s
      - name: Restart k8s deployment
        run: kubectl rollout restart deployment ${{ env.DEPLOYMENT_NAME }}
