name: deploy-identity

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    path: "src/IdentityService/**"
  pull_request:
    branches: ["main"]
    path: "src/IdentityService/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_PASSWORD}}
      - name: Build the Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: src/IdentityService/Dockerfile
          push: true
          tags: liamstan/ideneity-svc:latest
